"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { FormDialog } from "@/components/FormDialog";

type Approval={id:string;title:string;entity_type:string;amount?:number|string|null;requested_by?:string|null;status:string};
type Profile={id:string;email_snapshot?:string|null;role:string};
type Document={id:string;title:string;document_type:string;entity_type:string;created_at:string};
type Notification={id:string;recipient:string;title:string;message:string;severity:string;read:boolean};
const roles=["admin","director","manager","accountant","brick_manager","aluminium_manager","storekeeper","sales","fleet_manager","hr","driver","viewer"];

async function jsonRequest(path:string,method:string,body?:unknown){const r=await fetch(`/api/backend/${path}`,{method,headers:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(typeof p?.detail==="string"?p.detail:"Request failed");return p;}

export function GovernanceControl({approvals,profiles,documents,notifications}:{approvals:Approval[];profiles:Profile[];documents:Document[];notifications:Notification[]}){
 const router=useRouter();const [mode,setMode]=useState<"approval"|"document"|"notification">("approval");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 async function decide(id:string,status:string){const note=window.prompt(`${status} note (optional)`,"");try{await jsonRequest(`approvals/${id}`,"PATCH",{status,decision_note:note||null});router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not decide approval");}}
 async function roleChange(id:string,role:string){try{await jsonRequest(`profiles/${id}/role`,"PATCH",{role});setMessage("Role updated.");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not update role");}}
 async function submitApproval(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const f=new FormData(event.currentTarget);try{await jsonRequest("approvals","POST",{entity_type:String(f.get("entity_type")||"general"),entity_id:null,title:String(f.get("title")||""),amount:String(f.get("amount")||"")?Number(f.get("amount")):null});setMessage("Approval request created.");event.currentTarget.reset();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not create approval");}finally{setBusy(false);}}
 async function submitDocument(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{const response=await fetch("/api/backend/documents/upload",{method:"POST",body:form});const payload=await response.json().catch(()=>null);if(!response.ok)throw new Error(typeof payload?.detail==="string"?payload.detail:"Upload failed");setMessage("Document uploaded to the Tjekatjeka vault.");event.currentTarget.reset();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Upload failed");}finally{setBusy(false);}}
 async function submitNotification(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const f=new FormData(event.currentTarget);try{await jsonRequest("notifications","POST",{recipient:String(f.get("recipient")||""),title:String(f.get("title")||""),message:String(f.get("message")||""),severity:String(f.get("severity")||"info")});setMessage("Notification created.");event.currentTarget.reset();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not send notification");}finally{setBusy(false);}}
 return <>
  <FormDialog triggerLabel="Governance action" title="Governance action" description="Request approval, upload supporting evidence or create an internal notification while the control registers remain visible." eyebrow="Governance controls" size="wide">
   <section className="card entry-card"><div className="entry-head"><div><span className="eyebrow">Governance controls</span><h2>Approval, documents & communication</h2></div><div className="segmented"><button type="button" className={mode==="approval"?"active":""} onClick={()=>setMode("approval")}>Approval</button><button type="button" className={mode==="document"?"active":""} onClick={()=>setMode("document")}>Document</button><button type="button" className={mode==="notification"?"active":""} onClick={()=>setMode("notification")}>Notification</button></div></div>
    {mode==="approval"?<form className="entry-form" onSubmit={submitApproval}><label>Type<input name="entity_type" required placeholder="purchase / payroll / contract"/></label><label>Amount (M)<input name="amount" type="number" min="0" step="0.01"/></label><label className="span-2">Approval title<input name="title" required/></label>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions"><button className="action-button" disabled={busy}>{busy?"Saving…":"Request approval"}</button></div></form>:null}
    {mode==="document"?<form className="entry-form" onSubmit={submitDocument}><label>Related entity type<input name="entity_type" required placeholder="invoice / vehicle / employee"/></label><label>Related entity ID<input name="entity_id" placeholder="Optional UUID"/></label><label>Document title<input name="title" required/></label><label>Document type<input name="document_type" required placeholder="receipt / contract / licence"/></label><label className="span-2">File<input name="file" type="file" required/></label>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions"><button className="action-button" disabled={busy}>{busy?"Uploading…":"Upload document"}</button></div></form>:null}
    {mode==="notification"?<form className="entry-form" onSubmit={submitNotification}><label>Recipient email<input name="recipient" type="email" required/></label><label>Severity<select name="severity"><option value="info">Info</option><option value="success">Success</option><option value="warning">Warning</option><option value="critical">Critical</option></select></label><label className="span-2">Title<input name="title" required/></label><label className="span-2">Message<textarea name="message" required rows={3}/></label>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions"><button className="action-button" disabled={busy}>{busy?"Sending…":"Create notification"}</button></div></form>:null}
   </section>
  </FormDialog>
  <section className="section-grid">
   <div className="card table-card"><div className="table-title"><h2>Approval queue</h2><span>{approvals.filter(x=>x.status==="pending").length} pending</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Request</th><th>Type</th><th>Amount</th><th>Status</th><th>Decision</th></tr></thead><tbody>{approvals.map(x=><tr key={x.id}><td>{x.title}</td><td>{x.entity_type}</td><td>{x.amount==null?"—":`M ${Number(x.amount).toLocaleString("en-LS",{minimumFractionDigits:2})}`}</td><td>{x.status}</td><td>{x.status==="pending"?<div className="inline-actions"><button onClick={()=>decide(x.id,"approved")}>Approve</button><button onClick={()=>decide(x.id,"rejected")}>Reject</button></div>:"Decided"}</td></tr>)}</tbody></table></div></div>
   <div className="card table-card"><div className="table-title"><h2>Role administration</h2><span>{profiles.length} profiles</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Role</th></tr></thead><tbody>{profiles.map(x=><tr key={x.id}><td>{x.email_snapshot||"Provisioned user"}</td><td><select className="table-select" value={x.role} onChange={e=>roleChange(x.id,e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></td></tr>)}</tbody></table></div></div>
  </section>
  <section className="section-grid">
   <div className="card table-card"><div className="table-title"><h2>Document vault</h2><span>{documents.length} files</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Title</th><th>Type</th><th>Related to</th><th>Open</th></tr></thead><tbody>{documents.map(x=><tr key={x.id}><td>{x.title}</td><td>{x.document_type}</td><td>{x.entity_type}</td><td><a className="mini-action" href={`/api/backend/documents/${x.id}/download`}>Download</a></td></tr>)}</tbody></table></div></div>
   <div className="card table-card"><div className="table-title"><h2>Notifications</h2><span>{notifications.filter(x=>!x.read).length} unread</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Severity</th><th>Title</th><th>Recipient</th></tr></thead><tbody>{notifications.slice(0,25).map(x=><tr key={x.id}><td>{x.severity}</td><td>{x.title}</td><td>{x.recipient}</td></tr>)}</tbody></table></div></div>
  </section>
 </>;
}
