"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Account={id:string;code:string;name:string;account_type:string};
type Bank={id:string;name:string;bank_name:string;balance?:number|string};
type Transaction={id:string;description:string;reference?:string|null;amount:number|string;direction:string;reconciled:boolean;transaction_date:string};
type Line={account_id:string;debit:string;credit:string;memo:string};

async function request(path:string,method:string,body?:unknown){const r=await fetch(`/api/backend/${path}`,{method,headers:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(typeof p?.detail==="string"?p.detail:"Request failed");return p;}

export function LedgerControl({accounts,banks,transactions}:{accounts:Account[];banks:Bank[];transactions:Transaction[]}){
 const router=useRouter();const [mode,setMode]=useState<"journal"|"account"|"bank"|"transaction">("journal");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [lines,setLines]=useState<Line[]>([{account_id:"",debit:"",credit:"",memo:""},{account_id:"",debit:"",credit:"",memo:""}]);
 async function submit(event:FormEvent<HTMLFormElement>,path:string,build:(f:FormData)=>unknown,success:string){event.preventDefault();setBusy(true);setMessage("");try{await request(path,"POST",build(new FormData(event.currentTarget)));setMessage(success);event.currentTarget.reset();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Request failed");}finally{setBusy(false);}}
 async function reconcile(id:string){try{await request(`bank-transactions/${id}/reconcile`,"POST");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not reconcile");}}
 const button=(label:string)=><button className="action-button" disabled={busy}>{busy?"Saving…":label}</button>;
 return <>
  <section className="card entry-card"><div className="entry-head"><div><span className="eyebrow">Accounting control</span><h2>Post & reconcile</h2></div><div className="segmented"><button type="button" className={mode==="journal"?"active":""} onClick={()=>setMode("journal")}>Journal</button><button type="button" className={mode==="account"?"active":""} onClick={()=>setMode("account")}>Account</button><button type="button" className={mode==="bank"?"active":""} onClick={()=>setMode("bank")}>Bank</button><button type="button" className={mode==="transaction"?"active":""} onClick={()=>setMode("transaction")}>Bank transaction</button></div></div>
  {mode==="journal"?<form className="entry-form" onSubmit={e=>submit(e,"journals",f=>({reference:String(f.get("reference")||""),description:String(f.get("description")||""),entry_date:String(f.get("entry_date")||""),source_type:String(f.get("source_type")||"")||null,source_id:null,lines:lines.map(x=>({account_id:x.account_id,debit:Number(x.debit||0),credit:Number(x.credit||0),memo:x.memo||null}))}),"Balanced journal posted.")}><label>Reference<input name="reference" required placeholder="JNL-2026-001"/></label><label>Date<input name="entry_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label className="span-2">Description<input name="description" required/></label><label>Source type<input name="source_type" placeholder="manual / invoice / payroll"/></label><div className="span-2 input-builder"><div className="builder-head"><strong>Debit / credit lines</strong><button type="button" onClick={()=>setLines(v=>[...v,{account_id:"",debit:"",credit:"",memo:""}])}>+ Add line</button></div>{lines.map((line,i)=><div className="journal-line" key={i}><select required value={line.account_id} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,account_id:e.target.value}:x))}><option value="">Account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Debit" value={line.debit} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,debit:e.target.value}:x))}/><input type="number" min="0" step="0.01" placeholder="Credit" value={line.credit} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,credit:e.target.value}:x))}/><input placeholder="Memo" value={line.memo} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,memo:e.target.value}:x))}/>{lines.length>2?<button type="button" className="remove-button" onClick={()=>setLines(v=>v.filter((_,n)=>n!==i))}>Remove</button>:null}</div>)}</div>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions">{button("Post journal")}</div></form>:null}
  {mode==="account"?<form className="entry-form" onSubmit={e=>submit(e,"ledger-accounts",f=>({code:String(f.get("code")||""),name:String(f.get("name")||""),account_type:String(f.get("account_type")||"")}),"Ledger account created.")}><label>Code<input name="code" required/></label><label>Name<input name="name" required/></label><label>Type<select name="account_type" required><option value="asset">Asset</option><option value="liability">Liability</option><option value="equity">Equity</option><option value="income">Income</option><option value="expense">Expense</option></select></label>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions">{button("Create account")}</div></form>:null}
  {mode==="bank"?<form className="entry-form" onSubmit={e=>submit(e,"bank-accounts",f=>({name:String(f.get("name")||""),bank_name:String(f.get("bank_name")||""),account_mask:String(f.get("account_mask")||""),currency:"LSL",opening_balance:Number(f.get("opening_balance")||0)}),"Bank account created.")}><label>Account name<input name="name" required/></label><label>Bank<input name="bank_name" required/></label><label>Account mask<input name="account_mask" required placeholder="****1234"/></label><label>Opening balance<input name="opening_balance" type="number" step="0.01" defaultValue="0"/></label>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions">{button("Add bank account")}</div></form>:null}
  {mode==="transaction"?<form className="entry-form" onSubmit={e=>submit(e,"bank-transactions",f=>({bank_account_id:String(f.get("bank_account_id")||""),transaction_date:String(f.get("transaction_date")||""),description:String(f.get("description")||""),reference:String(f.get("reference")||"")||null,amount:Number(f.get("amount")||0),direction:String(f.get("direction")||"in"),journal_entry_id:null}),"Bank transaction recorded.")}><label>Bank account<select name="bank_account_id" required defaultValue=""><option value="">Select bank</option>{banks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Date<input name="transaction_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Description<input name="description" required/></label><label>Reference<input name="reference"/></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Direction<select name="direction"><option value="in">Money in</option><option value="out">Money out</option></select></label>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions">{button("Record transaction")}</div></form>:null}
  </section>
  <section className="card table-card"><div className="table-title"><h2>Bank reconciliation</h2><span>{transactions.filter(x=>!x.reconciled).length} unreconciled</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Description</th><th>Direction</th><th>Amount</th><th>Status</th></tr></thead><tbody>{transactions.map(x=><tr key={x.id}><td>{x.transaction_date}</td><td>{x.description}</td><td>{x.direction}</td><td>M {Number(x.amount||0).toLocaleString("en-LS",{minimumFractionDigits:2})}</td><td>{x.reconciled?<span className="status-chip ok">Reconciled</span>:<button className="mini-action" onClick={()=>reconcile(x.id)}>Reconcile</button>}</td></tr>)}</tbody></table></div></section>
 </>;
}
