"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { FormDialog } from "@/components/FormDialog";

type Branch={id:string;name:string};
type Employee={id:string;employee_no:string;full_name:string;job_title:string;basic_salary:number|string;active:boolean};
type Payroll={id:string;period_label:string;pay_date:string;status:string;gross_total:number|string;deduction_total:number|string;net_total:number|string};
type Slip={employee_id:string;allowances:string;deductions:string;notes:string};

async function request(path:string,method:string,body?:unknown){const r=await fetch(`/api/backend/${path}`,{method,headers:{"Content-Type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(typeof p?.detail==="string"?p.detail:"Request failed");return p;}

export function PeopleControl({branches,employees,payrolls}:{branches:Branch[];employees:Employee[];payrolls:Payroll[]}){
 const router=useRouter();const [mode,setMode]=useState<"employee"|"payroll">("employee");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [slips,setSlips]=useState<Slip[]>([{employee_id:"",allowances:"0",deductions:"0",notes:""}]);
 async function submit(event:FormEvent<HTMLFormElement>,path:string,build:(f:FormData)=>unknown,success:string){event.preventDefault();setBusy(true);setMessage("");try{await request(path,"POST",build(new FormData(event.currentTarget)));setMessage(success);event.currentTarget.reset();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Request failed");}finally{setBusy(false);}}
 async function statusChange(id:string,status:string){try{await request(`payroll-runs/${id}`,"PATCH",{status});setMessage(`Payroll marked ${status}.`);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Could not update payroll");}}
 return <>
  <FormDialog triggerLabel="People action" title="Employees & payroll" description="Create an employee or prepare a payroll run while keeping payroll history visible on the main page." eyebrow="People operations" size="wide">
   <section className="card entry-card"><div className="entry-head"><div><span className="eyebrow">People operations</span><h2>Employees & payroll</h2></div><div className="segmented"><button type="button" className={mode==="employee"?"active":""} onClick={()=>setMode("employee")}>Employee</button><button type="button" className={mode==="payroll"?"active":""} onClick={()=>setMode("payroll")}>Payroll run</button></div></div>
    {mode==="employee"?<form className="entry-form" onSubmit={e=>submit(e,"employees",f=>({branch_id:String(f.get("branch_id")||"")||null,employee_no:String(f.get("employee_no")||""),full_name:String(f.get("full_name")||""),job_title:String(f.get("job_title")||""),phone:String(f.get("phone")||"")||null,email:String(f.get("email")||"")||null,basic_salary:Number(f.get("basic_salary")||0),hired_date:String(f.get("hired_date")||"")}),"Employee created.")}><label>Employee number<input name="employee_no" required placeholder="EMP-001"/></label><label>Full name<input name="full_name" required/></label><label>Job title<input name="job_title" required/></label><label>Branch<select name="branch_id" defaultValue=""><option value="">Company / shared</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Phone<input name="phone"/></label><label>Email<input name="email" type="email"/></label><label>Basic salary (M)<input name="basic_salary" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Hired date<input name="hired_date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions"><button className="action-button" disabled={busy}>{busy?"Saving…":"Create employee"}</button></div></form>:null}
    {mode==="payroll"?<form className="entry-form" onSubmit={e=>submit(e,"payroll-runs",f=>({period_label:String(f.get("period_label")||""),pay_date:String(f.get("pay_date")||""),payslips:slips.map(x=>({employee_id:x.employee_id,allowances:Number(x.allowances||0),deductions:Number(x.deductions||0),notes:x.notes||null}))}),"Payroll prepared and sent for governance approval.")}><label>Period<input name="period_label" required placeholder="September 2026"/></label><label>Pay date<input name="pay_date" type="date" required/></label><div className="span-2 input-builder"><div className="builder-head"><strong>Payslips</strong><button type="button" onClick={()=>setSlips(v=>[...v,{employee_id:"",allowances:"0",deductions:"0",notes:""}])}>+ Add employee</button></div>{slips.map((s,i)=><div className="payroll-line" key={i}><select required value={s.employee_id} onChange={e=>setSlips(v=>v.map((x,n)=>n===i?{...x,employee_id:e.target.value}:x))}><option value="">Employee</option>{employees.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.full_name} · M {Number(x.basic_salary||0).toLocaleString("en-LS")}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Allowances" value={s.allowances} onChange={e=>setSlips(v=>v.map((x,n)=>n===i?{...x,allowances:e.target.value}:x))}/><input type="number" min="0" step="0.01" placeholder="Deductions" value={s.deductions} onChange={e=>setSlips(v=>v.map((x,n)=>n===i?{...x,deductions:e.target.value}:x))}/><input placeholder="Notes" value={s.notes} onChange={e=>setSlips(v=>v.map((x,n)=>n===i?{...x,notes:e.target.value}:x))}/>{slips.length>1?<button type="button" className="remove-button" onClick={()=>setSlips(v=>v.filter((_,n)=>n!==i))}>Remove</button>:null}</div>)}</div>{message?<div className="form-feedback success">{message}</div>:null}<div className="form-actions"><button className="action-button" disabled={busy}>{busy?"Saving…":"Prepare payroll"}</button></div></form>:null}
   </section>
  </FormDialog>
  <section className="card table-card"><div className="table-title"><h2>Payroll history</h2><span>Approval required before payment</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Period</th><th>Pay date</th><th>Status</th><th>Gross</th><th>Deductions</th><th>Net</th><th>Action</th></tr></thead><tbody>{payrolls.map(p=><tr key={p.id}><td>{p.period_label}</td><td>{p.pay_date}</td><td>{p.status}</td><td>M {Number(p.gross_total||0).toLocaleString("en-LS",{minimumFractionDigits:2})}</td><td>M {Number(p.deduction_total||0).toLocaleString("en-LS",{minimumFractionDigits:2})}</td><td>M {Number(p.net_total||0).toLocaleString("en-LS",{minimumFractionDigits:2})}</td><td><div className="inline-actions">{p.status==="draft"?<button onClick={()=>statusChange(p.id,"approved")}>Mark approved</button>:null}{p.status==="approved"?<button onClick={()=>statusChange(p.id,"paid")}>Mark paid</button>:null}</div></td></tr>)}</tbody></table></div></section>
 </>;
}
